Repository 98OO/colla-backend, pull requests merged in 2024-04, with the labels that each got.

#2 초기 프로젝트 설정
  .editorconfig
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  build.gradle
  commitlint.config.js
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  package-lock.json
  package.json
  rule-config/naver-checkstyle-rules.xml
  rule-config/naver-checkstyle-suppressions.xml
  settings.gradle
  src/main/java/one/colla/CollaBackendApplication.java
  src/main/resources/application.properties
  src/test/java/one/colla/CollaBackendApplicationTests.java
Labels: ✨ Feature

#6 Commit 전 Code Convention을 확인하도록 설정
  .editorconfig
  .husky/commit-msg
  .husky/pre-commit
  build.gradle
Labels: 🔨 Refactor

#8 Spring REST Docs + Swagger UI 설정
  .gitignore
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/one/colla/global/RestDocsControllerTestBase.java
  src/test/java/one/colla/global/TemporaryRestDocsControllerTest.java
  src/test/java/one/colla/global/config/RestDocsConfiguration.java
Labels: ⚙️ Configuration

#11 데이터베이스 구축을 위한 Docker 구성
  .gitignore
  docker/docker-compose.yml
Labels: 🚧 Infrastructure

#13 도메인별 Entity 작성
  docker/docker-compose.yml
  sql/init.sql
  src/main/java/one/colla/chat/domain/ChatChannel.java
  src/main/java/one/colla/chat/domain/ChatChannelMessage.java
  src/main/java/one/colla/chat/domain/ChatChannelMessageAttachment.java
  src/main/java/one/colla/chat/domain/Type.java
  src/main/java/one/colla/chat/domain/UserChatChannel.java
  src/main/java/one/colla/common/domain/BaseEntity.java
  src/main/java/one/colla/common/domain/CompositeKeyBase.java
  src/main/java/one/colla/feed/collect/domain/CollectFeed.java
  src/main/java/one/colla/feed/collect/domain/CollectFeedResponse.java
  src/main/java/one/colla/feed/collect/domain/Status.java
  src/main/java/one/colla/feed/common/domain/Comment.java
  src/main/java/one/colla/feed/common/domain/Feed.java
  src/main/java/one/colla/feed/common/domain/FeedAttachment.java
  src/main/java/one/colla/feed/common/domain/FeedType.java
  src/main/java/one/colla/feed/normal/domain/NormalFeed.java
  src/main/java/one/colla/feed/scheduling/domain/SchedulingFeed.java
  src/main/java/one/colla/feed/scheduling/domain/SchedulingFeedAvailableTime.java
  src/main/java/one/colla/feed/scheduling/domain/SchedulingFeedTargetDate.java
  src/main/java/one/colla/feed/vote/domain/VoteFeed.java
  src/main/java/one/colla/feed/vote/domain/VoteFeedOption.java
  src/main/java/one/colla/feed/vote/domain/VoteFeedSelection.java
  src/main/java/one/colla/file/domain/Attachment.java
  src/main/java/one/colla/file/domain/Type.java
  src/main/java/one/colla/global/config/JpaConfig.java
  src/main/java/one/colla/schedule/domain/CalendarEvent.java
  src/main/java/one/colla/schedule/domain/CalendarEventFeed.java
  src/main/java/one/colla/schedule/domain/CalendarEventFeedLink.java
  src/main/java/one/colla/schedule/domain/CalendarEventSchedule.java
  src/main/java/one/colla/schedule/domain/CalendarEventSubtodo.java
  src/main/java/one/colla/schedule/domain/CalendarEventTodo.java
  src/main/java/one/colla/schedule/domain/CalendarEventType.java
  src/main/java/one/colla/schedule/domain/Status.java
  src/main/java/one/colla/schedule/domain/UserCalendarEvent.java
  src/main/java/one/colla/schedule/domain/UserCalendarEventMention.java
  src/main/java/one/colla/teamspace/domain/Tag.java
  src/main/java/one/colla/teamspace/domain/Teamspace.java
  src/main/java/one/colla/teamspace/domain/UserTeamspace.java
  src/main/java/one/colla/user/domain/CommentNotification.java
  src/main/java/one/colla/user/domain/OauthApproval.java
  src/main/java/one/colla/user/domain/Role.java
  src/main/java/one/colla/user/domain/User.java
  src/main/java/one/colla/user/domain/UserRepository.java
Labels: ✨ Feature

#16 공통 응답 및 에러 처리 작성 #14
  src/main/java/one/colla/common/presentation/ApiResponse.java
  src/main/java/one/colla/global/exception/CommonException.java
  src/main/java/one/colla/global/exception/ExceptionCode.java
  src/main/java/one/colla/global/exception/GlobalExceptionHandler.java
  src/test/java/one/colla/common/presentation/ApiResponseTest.java
Labels: ✨ Feature

#17 인증 및 인가 구현을 위한 초기 설정
  src/main/java/one/colla/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/one/colla/common/security/filter/JwtExceptionFilter.java
  src/main/java/one/colla/common/security/handler/JwtAccessDeniedHandler.java
  src/main/java/one/colla/common/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/one/colla/global/config/security/CorsConfig.java
  src/main/java/one/colla/global/config/security/SecurityAuthConfig.java
  src/main/java/one/colla/global/config/security/SecurityConfig.java
  src/main/java/one/colla/global/config/security/SecurityFilterConfig.java
Labels: ⚙️ Configuration

#20 chore: logback을 사용한 logging 적용
  .gitignore
  build.gradle
  src/main/resources/logback-spring.xml
Labels: ⚙️ Configuration

#26 자체 회원 로그인 및 JWT 기반 인증•인가 구현
  build.gradle
  docker/docker-compose.yml
  src/main/java/one/colla/auth/application/AuthService.java
  src/main/java/one/colla/auth/application/JwtService.java
  src/main/java/one/colla/auth/application/dto/JwtPair.java
  src/main/java/one/colla/auth/application/dto/request/LoginRequest.java
  src/main/java/one/colla/auth/application/dto/response/LoginResponse.java
  src/main/java/one/colla/auth/presentation/AuthController.java
  src/main/java/one/colla/common/presentation/ApiResponse.java
  src/main/java/one/colla/common/security/authentication/CustomUserDetails.java
  src/main/java/one/colla/common/security/authentication/UserDetailServiceImpl.java
  src/main/java/one/colla/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/one/colla/common/security/filter/JwtExceptionFilter.java
  src/main/java/one/colla/common/security/handler/JwtAccessDeniedHandler.java
  src/main/java/one/colla/common/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/one/colla/common/security/jwt/JwtClaims.java
  src/main/java/one/colla/common/security/jwt/JwtProvider.java
  src/main/java/one/colla/common/security/jwt/access/AccessTokenClaim.java
  src/main/java/one/colla/common/security/jwt/access/AccessTokenClaimKeys.java
  src/main/java/one/colla/common/security/jwt/access/AccessTokenProvider.java
  src/main/java/one/colla/common/security/jwt/refresh/RefreshTokenClaim.java
  src/main/java/one/colla/common/security/jwt/refresh/RefreshTokenClaimKeys.java
  src/main/java/one/colla/common/security/jwt/refresh/RefreshTokenProvider.java
  src/main/java/one/colla/common/util/CookieUtil.java
  src/main/java/one/colla/global/config/security/MethodSecurityConfig.java
  src/main/java/one/colla/global/config/security/SecurityAuthConfig.java
  src/main/java/one/colla/global/config/security/SecurityConfig.java
  src/main/java/one/colla/global/config/security/SecurityFilterConfig.java
  src/main/java/one/colla/global/exception/ExceptionCode.java
  src/main/java/one/colla/global/exception/GlobalExceptionHandler.java
  src/main/java/one/colla/global/handler/GlobalExceptionHandler.java
  src/main/java/one/colla/infra/config/RedisConfig.java
  src/main/java/one/colla/infra/redis/forbidden/ForbiddenToken.java
  src/main/java/one/colla/infra/redis/forbidden/ForbiddenTokenRepository.java
  src/main/java/one/colla/infra/redis/forbidden/ForbiddenTokenService.java
  src/main/java/one/colla/infra/redis/refresh/RefreshToken.java
  src/main/java/one/colla/infra/redis/refresh/RefreshTokenRepository.java
  src/main/java/one/colla/infra/redis/refresh/RefreshTokenService.java
  src/main/java/one/colla/infra/redis/refresh/RefreshTokenServiceImpl.java
  src/main/java/one/colla/user/application/UserAuthService.java
  src/main/java/one/colla/user/application/UserService.java
  src/main/java/one/colla/user/domain/UserRepository.java
  src/main/java/one/colla/user/presentation/UserAuthController.java
  src/main/resources/application.yml
  src/test/java/one/colla/common/presentation/ApiResponseTest.java
  src/test/java/one/colla/common/security/jwt/access/AccessTokenProviderTest.java
  src/test/java/one/colla/global/exception/ExceptionCodeTest.java
Labels: ✨ Feature
