Repository 98OO/colla-backend, pull requests merged in 2024-05, with the labels that each got.

#34 소셜 회원 가입 및 로그인 구현
  sql/init.sql
  src/main/java/one/colla/auth/application/AuthService.java
  src/main/java/one/colla/auth/application/OAuthClient.java
  src/main/java/one/colla/auth/application/OAuthService.java
  src/main/java/one/colla/auth/application/OAuthUserCreator.java
  src/main/java/one/colla/auth/application/dto/oauth/OAuthTokenResponse.java
  src/main/java/one/colla/auth/application/dto/oauth/OAuthUserInfo.java
  src/main/java/one/colla/auth/application/dto/request/OAuthLoginRequest.java
  src/main/java/one/colla/auth/application/dto/response/OauthLoginUrlResponse.java
  src/main/java/one/colla/auth/config/GoogleOAuthProperties.java
  src/main/java/one/colla/auth/config/KakaoOAuthProperties.java
  src/main/java/one/colla/auth/config/NaverOAuthProperties.java
  src/main/java/one/colla/auth/config/OAuthProperties.java
  src/main/java/one/colla/auth/config/OAuthPropertyFactory.java
  src/main/java/one/colla/auth/presentation/AuthController.java
  src/main/java/one/colla/common/presentation/ApiResponse.java
  src/main/java/one/colla/common/util/StringToProviderConverter.java
  src/main/java/one/colla/common/util/TokenParser.java
  src/main/java/one/colla/common/util/oauth/OAuthUriGenerator.java
  src/main/java/one/colla/common/util/oauth/OAuthUriGeneratorImpl.java
  src/main/java/one/colla/global/config/WebConfig.java
  src/main/java/one/colla/global/exception/ExceptionCode.java
  src/main/java/one/colla/global/handler/GlobalExceptionHandler.java
  src/main/java/one/colla/user/domain/OauthApproval.java
  src/main/java/one/colla/user/domain/OauthApprovalRepository.java
  src/main/java/one/colla/user/domain/Provider.java
  src/main/java/one/colla/user/domain/User.java
  src/main/java/one/colla/user/domain/vo/Password.java
  src/main/java/one/colla/user/domain/vo/ProfileImageUrl.java
  src/main/resources/application.yml
  src/test/java/one/colla/auth/application/AuthServiceTest.java
  src/test/java/one/colla/auth/application/OAuthClientTest.java
  src/test/java/one/colla/auth/application/OAuthServiceTest.java
  src/test/java/one/colla/auth/application/OAuthUserCreatorTest.java
  src/test/java/one/colla/auth/application/config/OAuthPropertiesFactoryTest.java
  src/test/java/one/colla/auth/presentation/AuthControllerTest.java
  src/test/java/one/colla/common/CommonTest.java
  src/test/java/one/colla/common/util/TokenParserTest.java
  src/test/java/one/colla/common/util/oauth/OAuthUriGeneratorImplTest.java
  src/test/java/one/colla/global/TemporaryRestDocsControllerTest.java
  src/test/java/one/colla/user/domain/UserRepositoryTest.java
  src/test/java/one/colla/user/domain/vo/PasswordTest.java
Labels: ✨ Feature

#37 배포 환경 구축 2차
  .github/workflows/continuous-deploy.yml
  .gitignore
  Dockerfile
  build.gradle
  docker-infra/docker-compose.yml
Labels: ⚙️ Configuration, 🚧 Infrastructure

#43 팀 스페이스 사용자 정보 관련
  build.gradle
  src/main/java/one/colla/auth/application/JwtService.java
  src/main/java/one/colla/auth/application/OAuthService.java
  src/main/java/one/colla/auth/application/OAuthUserCreator.java
  src/main/java/one/colla/auth/application/dto/response/LoginResponse.java
  src/main/java/one/colla/auth/config/OAuthPropertyFactory.java
  src/main/java/one/colla/auth/presentation/AuthController.java
  src/main/java/one/colla/chat/domain/ChatChannelMessage.java
  src/main/java/one/colla/chat/domain/ChatType.java
  src/main/java/one/colla/common/domain/vo/Url.java
  src/main/java/one/colla/common/security/authentication/CustomUserDetails.java
  src/main/java/one/colla/common/util/StringToProviderConverter.java
  src/main/java/one/colla/feed/collect/domain/CollectFeedResponse.java
  src/main/java/one/colla/feed/collect/domain/CollectFeedStatus.java
  src/main/java/one/colla/file/domain/Attachment.java
  src/main/java/one/colla/file/domain/AttachmentType.java
  src/main/java/one/colla/infra/redis/lastseen/LastSeenTeamspace.java
  src/main/java/one/colla/infra/redis/lastseen/LastSeenTeamspaceRepository.java
  src/main/java/one/colla/infra/redis/lastseen/LastSeenTeamspaceService.java
  src/main/java/one/colla/infra/redis/lastseen/LastSeenTeamspaceServiceImpl.java
  src/main/java/one/colla/schedule/domain/CalendarEventSubtodo.java
  src/main/java/one/colla/schedule/domain/CalendarEventTodo.java
  src/main/java/one/colla/schedule/domain/CalendarEventTodoStatus.java
  src/main/java/one/colla/teamspace/application/TeamspaceService.java
  src/main/java/one/colla/teamspace/domain/Teamspace.java
  src/main/java/one/colla/teamspace/domain/vo/TeamspaceProfileImageUrl.java
  src/main/java/one/colla/user/application/UserService.java
  src/main/java/one/colla/user/application/dto/request/LastSeenUpdateRequest.java
  src/main/java/one/colla/user/application/dto/response/ParticipatedTeamspaceDto.java
  src/main/java/one/colla/user/application/dto/response/ProfileDto.java
  src/main/java/one/colla/user/application/dto/response/UserStatusResponse.java
  src/main/java/one/colla/user/domain/OauthApproval.java
  src/main/java/one/colla/user/domain/OauthProvider.java
  src/main/java/one/colla/user/domain/User.java
  src/main/java/one/colla/user/domain/UserRole.java
  src/main/java/one/colla/user/domain/vo/ProfileImageUrl.java
  src/main/java/one/colla/user/domain/vo/UserProfileImageUrl.java
  src/main/java/one/colla/user/presentation/UserController.java
  src/test/java/one/colla/auth/application/OAuthServiceTest.java
  src/test/java/one/colla/auth/application/OAuthUserCreatorTest.java
  src/test/java/one/colla/auth/application/config/OAuthPropertiesFactoryTest.java
  src/test/java/one/colla/auth/presentation/AuthControllerTest.java
  src/test/java/one/colla/common/fixtures/UserFixtures.java
  src/test/java/one/colla/teamspace/domain/vo/TeamspaceProfileImageUrlTest.java
  src/test/java/one/colla/user/application/UserServiceTest.java
  src/test/java/one/colla/user/domain/vo/UserProfileImageUrlTest.java
  src/test/java/one/colla/user/presentation/UserControllerTest.java
Labels: ✨ Feature

#51 마이페이지 설정 관련 api 개발
  src/main/java/one/colla/global/handler/GlobalExceptionHandler.java
  src/main/java/one/colla/teamspace/application/TeamspaceService.java
  src/main/java/one/colla/teamspace/domain/Teamspace.java
  src/main/java/one/colla/teamspace/presentation/TeamspaceController.java
  src/main/java/one/colla/user/application/UserService.java
  src/main/java/one/colla/user/application/dto/request/UpdateUserSettingRequest.java
  src/main/java/one/colla/user/domain/User.java
  src/main/java/one/colla/user/presentation/UserController.java
  src/main/resources/application.yml
  src/test/java/one/colla/teamspace/application/TeamspaceServiceTest.java
  src/test/java/one/colla/teamspace/application/dto/UpdateTeamspaceSettingsRequestValidationTest.java
  src/test/java/one/colla/teamspace/presentation/TeamspaceControllerTest.java
  src/test/java/one/colla/user/application/UpdateUserSettingRequestValidationTest.java
  src/test/java/one/colla/user/application/UserServiceTest.java
  src/test/java/one/colla/user/presentation/UserControllerTest.java
Labels: ✨ Feature

#53 Path Variable 관련 타입 불일치 예외 Handler 통일
  src/main/java/one/colla/common/presentation/ApiResponse.java
  src/main/java/one/colla/common/util/StringToProviderConverter.java
  src/main/java/one/colla/global/config/WebConfig.java
  src/main/java/one/colla/global/handler/GlobalExceptionHandler.java
Labels: 🔨 Refactor

#61 Attachments 테이블 name 필드 추가
  sql/V1_ATTACHMENTS_ADD_NAME.sql
  sql/init.sql
  src/main/java/one/colla/file/domain/Attachment.java
  src/main/java/one/colla/file/domain/vo/AttachmentName.java
  src/test/java/one/colla/file/domain/vo/AttachmentNameTest.java
Labels: ✨ Feature
